export const INIT_BREADCRUMB = 'INIT_BREADCRUMB';
export const ADD_BREADCRUMB = 'ADD_BREADCRUMB';
export const REMOVE_BREADCRUMB = 'REMOVE_BREADCRUMB';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_ROLENAME = 'SET_ROLENAME';
export const SET_MENUS = 'SET_MENUS';